name: AI-Powered Test Generation

on:
  workflow_dispatch:
    inputs:
      max_classes:
        description: 'Maximum number of classes to generate tests for'
        required: true
        default: '5'
      min_coverage:
        description: 'Minimum coverage percentage threshold'
        required: true
        default: '80'

jobs:
  generate-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: maven

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Python dependencies
        run: pip install requests

      # Add JaCoCo to parent POM for coverage reporting
      - name: Add JaCoCo to parent POM
        run: |
          mvn org.codehaus.mojo:versions-maven-plugin:2.15.0:set-property -Dproperty=jacoco.version -DnewVersion=0.8.12 -DgenerateBackupPoms=false
          mvn jacoco:prepare-agent test jacoco:report

      # Generate tests using SambaNova API
      - name: Generate tests
        env:
          SAMBANOVA_API_KEY: ${{ secrets.SAMBANOVA_API_KEY }}
        run: |
          python .github/scripts/test_generator.py \
            --max-classes ${{ github.event.inputs.max_classes }} \
            --min-coverage ${{ github.event.inputs.min_coverage }}

      # Create a PR with the generated tests
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "test: Add AI-generated tests to improve coverage"
          title: "test: Add AI-generated tests to improve coverage"
          branch: ai-generated-tests
          base: main